name: unittest-and-lint
on:
  # Run on all branch pushes
  push:
    branches: [ "*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Run linting
        run: |
          flake8 app/
          mypy app/ 
          isort app/ --check-only
          black app/ --check

      - name: Run unit tests
        run: |
          # Run tests
          python -m pytest app/tests/
